name: Unittests

on:
    push:
        branches:
            - master

    pull_request:
        branches:
            - '*'
jobs:
    run_hardhart_unittests:
        runs-on: ubuntu-latest
        name: Run the Hardhat unit tests
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js 14.x
              uses: actions/setup-node@v1
              with:
                  node-version: 14.x
            - run: npm install
            - run: npx hardhat test
