name: Linter

on:
    push:
        branches:
            - master

    pull_request:
        branches:
            - '*'
jobs:
    run_solidity_linter:
        runs-on: ubuntu-latest
        name: Run Solidity linter
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js 14.x
              uses: actions/setup-node@v1
              with:
                  node-version: 14.x
            - run: npm install
            - run: npx hardhat check
